### ISSUE TITLE
API v2

### ISSUE THREAD

**Issue by cyyynthia** [powercord-org/powercord-backend#21]
As the code right now is a huge unreadable gross bad mess, we'll rewrite the API and release it as a v2. If you have an idea of what we could ship in the update, feel free to propose it here or on the Powercord Discord server.

## Release schedule
Planned release date: [TBD]
API v1 removal: **With v2 release**

## Website
 - - [x] A better homepage than currently
 - - [ ] API Documentation (yes finally)
    - Maybe let plugins have their own docs if they intent on letting other plugins use their APIs
    - Basic tutorials on how to get started, with also some more advanced stuff like Flux basics
 - - [x] Fix #12 

## API
 - - [x] Make external services token refresh overall better
 - - [ ] Plugin and themes listing API
 - - [ ] Patreon integration (wish me luck their api is the worst meme i've ever seen)
 - - [ ] API to let users customize their badges settings
 - - [ ] Better internal tools to manage user badges, plugin, themes etc

## Powercord Bot
 - - [x] Add custom commands (tags) so we'll stop sending over and over the same thing
    - I'll probably let support and staff access to their management
 - - [x] Mute command and logs for people getting muted

**Comment by Bowser65** [comment]
https://canary.discordapp.com/channels/538759280057122817/538759280497786890/639963216440590366

**Comment by cal3432** [comment]
I got a suggestion for the Powercord bot.

- [ ] Search plugins/themes in the store (when it releases)
- [ ] Trigger words such as "plugin docs", this replies with a url to the docs etc.

**Comment by cyyynthia** [comment]
This issue is outdated, refer to the roadmap.md file
