### ISSUE TITLE
Server Issue when deleting account

### ISSUE THREAD

**Issue by UPPERCASEuser** [powercord-org/powercord-backend#24]
<h1 align=center>Issue:</h1>
When I try to delete my account, it loads infinitly the page and outputs a server error

![image](https://user-images.githubusercontent.com/27961224/71692827-bd6c9200-2d89-11ea-94bd-e6e7d4c50e71.png)

sry for my bad english

**Comment by Bowser65** [comment]
Should be fixed (and deployed) in d77753e7a3c275cde36f08494a0fc23bb3251a16
