### ISSUE TITLE
Allow Registering command icons

### ISSUE THREAD

**Issue by boehs** [powercord-org/powercord-backend#74]
Title: ![](https://e.reeee.ee/0A3vdV.png), I want to be able to set custom icons for commands and whatnot

## The ~~two~~three options

1. Module based icon
2. Command based icon
3. Somehow both?

### The both route

1. Sidebar icon is module icon
2. Each command can have its own icon that is shown when you are entering command arguments.
3. If not specified, defaults to module icon

**Comment by cyyynthia** [comment]
This is the repo for the powercord.dev website and REST API, not the repo for the Powercord client mod nor the repo to suggest things for the mod.

If you want to request a new plugin, you're probably looking for https://github.com/powercord-community/suggestions.

**Comment by boehs** [comment]
I am sorry! Wrote this issue at 1am 😊
