### ISSUE TITLE
Error: Unable to load profile banner, badges, and about me.

### ISSUE THREAD

**Issue by Sukooo** [powercord-org/powercord-backend#79]
Whenever i visit a discord profile of some, I don't have as an friend, it shows the following error: "Unable to load profile banner, badges, and about me.". Is this made to happen like this?

**Comment by cyyynthia** [comment]
This is not an issue with Powercord itself and certainly not the backend that has nothing to do with this. It may be Discord's API having a stroke, or a plugin rate-limiting you (like badges-everywhere).

For more help you should go to our support server and ask in the appropriated channel.
